apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-new-app 
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: my-new-app  
  template:
    metadata:
      labels:
        app: my-new-app 
    spec:
      containers:
      - name: my-new-streamlit
        image: athospugliese/case-ai-app:latest 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8501 
        env:
        - name: AGENT_URL
          value: "http://localhost:8000"  
        - name: STREAMLIT_SERVER_ENABLE_CORS
          value: "false"
        - name: STREAMLIT_SERVER_HEADLESS
          value: "true"
        - name: STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION
          value: "false"
        - name: PYTHONPATH
          value: "/app/src"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: OPENAI_API_KEY
        - name: DEEPSEEK_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DEEPSEEK_API_KEY
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: ANTHROPIC_API_KEY
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: GOOGLE_API_KEY
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: GROQ_API_KEY
        - name: TAVILY_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: TAVILY_API_KEY
        - name: LANGCHAIN_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: LANGCHAIN_API_KEY
        - name: OPENWEATHERMAP_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: OPENWEATHERMAP_API_KEY
        - name: LANGSMITH_TRACING
          value: "true"
        - name: LANGSMITH_PROJECT
          value: "pr-dependable-abnormality-65"
        - name: LANGCHAIN_ENDPOINT
          value: "https://api.smith.langchain.com"
        - name: DEFAULT_MODEL
          value: "gpt-4o-mini"
        command: ["streamlit", "run", "/app/src/app.py"]
      - name: my-new-fastapi
        image: athospugliese/case-ai-app:latest  
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000 
        env:
        - name: PYTHONPATH
          value: "/app/src"
        - name: AGENT_URL
          value: "http://127.0.0.1:8000"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: OPENAI_API_KEY
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: GROQ_API_KEY
        - name: LANGCHAIN_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: LANGCHAIN_API_KEY
        - name: LANGSMITH_TRACING
          value: "true"
        - name: LANGSMITH_PROJECT
          value: "pr-dependable-abnormality-65"
        - name: LANGCHAIN_ENDPOINT
          value: "https://api.smith.langchain.com"
        - name: DEFAULT_MODEL
          value: "gpt-4o-mini"
        command: ["uvicorn", "src.service.service:app", "--host", "0.0.0.0", "--port", "8000"]
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: my-new-app-service  
spec:
  type: LoadBalancer
  selector:
    app: my-new-app 
  ports:
  - name: fastapi
    protocol: TCP
    port: 8000 
    targetPort: 8000 
  - name: streamlit
    protocol: TCP
    port: 8501 
    targetPort: 8501 
