services:
  app:
    build: .
    ports:
      - "8501:8501"
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_HEADLESS=true
      - PYTHONPATH=/app/src
      - AGENT_URL=http://app:8000
    command: >
      sh -c "streamlit run src/app.py --server.port=8501 &
             uvicorn service.service:app --host 0.0.0.0 --port 8000"
